### ISSUE TITLE
Bug in @pega/auth@0.2.5, property of null

### ISSUE THREAD

**Issue by wimbarelds** [pegasystems/react-sdk#443] opened 2024-03-12 09:18 UTC
**Describe the bug**
I am well aware that this is not the repository for `@pega/auth`, but that repository does not exist (publicly), so I cannot report bugs in that repository in the correct place. This was the best place that I could find to report this bug.

The bug is this:
```js
// File: @pega/auth/lib/sdk-auth-manager/authManager.js

// line 546-548:
#customConstellationInit(fnReauth) {
  this.#constellationInit(null, null, null, fnReauth);
}

// line 451, function declaration of this.#constellationInit
#constellationInit(authConfig, tokenInfo, authTokenUpdated, fnReauth) {

// line 498, inside function body of this.#constellationInit
if (authConfig.serverType === 'launchpad') {
```

Resulting error: `Uncaught TypeError: Cannot read properties of null (reading 'serverType')`

**To Reproduce**
- Using `@pega/auth@0.2.5`
```js
import { loginIfNecessary, sdkSetAuthHeader } from '@pega/auth/lib/sdk-auth-manager/authManager.js';

sdkSetAuthHeader(`bearer ${token.access_token}`);
loginIfNecessary({ appName: 'myApp', mainRedirect: false});
```

**Expected behavior**
Expect not to get an error (and get a `SdkConstellationReady` event).

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.3.1
 - Browser Google Chrome
 - Version 121.0.6167.184 (Official Build) (arm64) 

**Additional context**
The function is called with argument value null for `authConfig`, the function tries to access properties of `authConfig` (which is null), therefor it errors. The code should check whether authConfig is truthy before trying to access properties of it.

**Comment by vrseraphin** [comment] 2024-03-15 18:56
Thanks for the very detailed report of this issue!
The issue is now resolved with @pega/auth@0.2.6

Please reopen or enter a new BUG if you find otherwise

**Closed** 2024-03-15 18:57 UTC
